model:
  img_size: 32
  in_channels: 3
  patch_size: 4
  emb_dim: 384
  ffn_dim_ratio: 4
  n_heads: 8
  num_layers: 8
  positional_encoding: 'sincos'
  p_pos_encoding_dropout: 0.05
  p_encoder_dropout: 0.20

  ema_model:
    decay: 0.999

train:
  data:
    num_training: 49000
    num_validation: 1000
    batch_size: 192
    drop_last: true
  optimizer:
    lr: 1.0e-4
    weight_decay: 1.0e-4
  scheduler:
    type: 'CosineAnnealingLR'
    eta_min: 1.0e-06
    warmup:
      type: 'linear'
      start_factor: 0.05
      epochs: 20
  process:
    epochs: 500

checkpoint:
  img_save_every_n_epochs: 10
  img_B: 10
  img_T: 100
  model_save_every_n_epochs: 2
  saveroot: results/
