model:
  img_size: 32
  in_channels: 3
  patch_size: 4
  emb_dim: 384
  ffn_dim_ratio: 4
  n_heads: 8
  num_layers: 8
  positional_encoding: 'sincos'
  p_pos_encoding_dropout: 0.0
  p_encoder_dropout: 0.0

  ema_model:
    decay: 0.85

train:
  data:
    num_training: 1
    num_validation: 10
    batch_size: 32
    drop_last: true
  optimizer:
    lr: 0.0003
    weight_decay: 0.0
  process:
    epochs: 500
  scheduler:
    type: 'CosineAnnealingLR'
    eta_min: 1.0e-06

checkpoint:
  img_save_every_n_epochs: 100
  img_B: 2
  img_T: 100
  model_save_every_n_epochs: 100
  saveroot: results/
